# Generated by Django 3.2 on 2021-07-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_pago', models.IntegerField(choices=[[0, 'debito'], [1, 'credito'], [2, 'transferencia']])),
                ('avisos', models.BooleanField()),
            ],
        ),
    ]
