# Generated by Django 3.2 on 2021-07-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_suscriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscriptor',
            name='monto_donacion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='avisos',
            field=models.IntegerField(choices=[[0, 'si'], [1, 'no']]),
        ),
    ]
